<?php
/**
 * Created by PhpStorm.
 * User: pengjiang
 * Date: 2019/5/14
 * Time: 18:26
 */

namespace app\common\controller;


class UserBase extends Base
{
    protected $uid = 0;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $reids = redis();
        $reids->setKey($this->project);
    
        $token = request()->header("token");
        if (empty($token)) {
            $this->error(lang('token_expired'));
        }
        $this->uid = $uid = $reids->get("members:" . $token);
        if (empty($uid)) {
            $this->error(lang('token_expired'));
        }
    }
}